version: '3'

services:
  rep-log-master:
    build: ReplicatedLogMaster
    command: ["dotnet", "ReplicatedLogMaster.dll"]
    environment:
      MASTER_HOST: '*'
      MASTER_PORT: 2100
      SECONDARIES_NUM: 2
      SECONDARY1_HOST: 'rep-log-secondary-1'
      SECONDARY1_PORT: 5001
      SECONDARY2_HOST: 'rep-log-secondary-2'
      SECONDARY2_PORT: 5002
      BROADCASTING_TIME_OUT: 20
      RETRY_TIME_OUT: 300
      PING_DELAY: 5
      RETRY_DELAY: 5
      QUORUM: 2
      BATCH_SIZE: 2
    ports:
      - "2100:2100"
    networks:
      - rep-log-master-net

  rep-log-secondary-1:
    build: ReplicatedLogSecondary2
    command: ["python", "service.py"]
    environment:
      SECONDARY_HOST: '0.0.0.0'
      SECONDARY_PORT: 5001
      POST_DELAY: 0
      ERROR_BEFORE_EVEN_MESSAGE: 'false'
      ERROR_AFTER_EVEN_MESSAGE: 'false'
    ports:
      - "2201:5001"
    networks:
      - rep-log-master-net


  rep-log-secondary-2:
    build: ReplicatedLogSecondary2
    command: ["python", "service.py"]
    environment:
      SECONDARY_HOST: '0.0.0.0'
      SECONDARY_PORT: 5002
      POST_DELAY: 0
      ERROR_BEFORE_EVEN_MESSAGE: 'false'
      ERROR_AFTER_EVEN_MESSAGE: 'false'
    ports:
      - "2202:5002"
    networks:
      - rep-log-master-net

networks:
    rep-log-master-net:
