version: '3'

services:
  rep-log-master:
    build: ReplicatedLogMaster
    command: ["dotnet", "ReplicatedLogMaster.dll"]
    environment:
      MASTER_HOST: '*'
      MASTER_PORT: 2100
      SECONDARIES_NUM: 2
      SECONDARY1_HOST: 'rep-log-secondary-1'
      SECONDARY1_PORT: 3000
      SECONDARY2_HOST: 'rep-log-secondary-2'
      SECONDARY2_PORT: 5000
      BROADCASTING_TIME_OUT: 20000
    ports:
      - "2100:2100"
    networks:
      - rep-log-master-net

  rep-log-secondary-1:
    build: ReplicatedLogSecondary1
    command: ["node", "server.js"]
    environment:
      SECONDARY1_HOST: '*'
      SECONDARY1_PORT: 3000
      POST_DELAY: 10
    ports:
      - "2201:3000"
    networks:
      - rep-log-master-net


  rep-log-secondary-2:
    build: ReplicatedLogSecondary2
    command: ["python", "service.py"]
    environment:
      SECONDARY_HOST: '0.0.0.0'
      SECONDARY_PORT: 5000
      POST_DELAY: 10
    ports:
      - "2202:5000"
    networks:
      - rep-log-master-net

networks:
    rep-log-master-net:
