version: '3'

services:
  rep-log-master:
    build: ReplicatedLogMaster
    command: ["dotnet", "ReplicatedLogMaster.dll"]
    environment:
      MASTER_HOST: '*'
      MASTER_PORT: 2100
      SLAVE1_HOST: 'rep-log-slave-1'
      SLAVE1_PORT: 3000
      SLAVE2_HOST: 'rep-log-slave-2'
      SLAVE2_PORT: 5000
    ports:
      - 2100:2100
    networks:
      - rep-log-master-net

  rep-log-slave-1:
    build: ReplicatedLogSecondary1
    command: ["node", "server.js"]
    environment:
      SLAVE1_HOST: '*'
      POST_DELAY: 5000
      SLAVE1_PORT: 3000
    ports:
      - 2201:3000
    networks:
      - rep-log-master-net


  rep-log-slave-2:
    build: ReplicatedLogSecondary2
    command: ["python", "service.py"]
    environment:
      SLAVE_HOST: '0.0.0.0'
      SLAVE_PORT: 5000
    ports:
      - 2202:5000
    networks:
      - rep-log-master-net

networks:
    rep-log-master-net:
