version: '3'

services:
  rep-log-master:
    build: .
    command: ["dotnet", "ReplicatedLogMaster.dll"]
    environment:
      MASTER_HOST: '*'
      MASTER_PORT: 2100
      SLAVE1_HOST: 'localhost'
      SLAVE1_PORT: 2200
    ports:
      - 2100:2100