version: '3'

services:
  rep-log-secondary-2:
    build: .
    command: ["python", "service.py"]
    environment:
      SECONDARY_HOST: '0.0.0.0'
      SECONDARY_PORT: 5000
    ports:
      - 2202:5000
